services:

  mysql-prod:
    image: mysql:8.0.35-debian
    container_name: backend-mysql-prod
    restart: always

    command: --ssl=0 --skip-ssl

    env_file:
      - .env

    volumes:
      - mysql_data_prod:/var/lib/mysql
      - ./docker/mysql/films_dump.sql:/docker-entrypoint-initdb.d/films_dump.sql

    ports:
      - "3306:3306"


  apache-prod:
    build: ./docker/apache
    container_name: backend-apache-prod
    restart: always

    ports:
      - "8080:80"

    volumes:
      - ./app:/var/www/html
      - ./logs:/var/log/apache2/custom
      - ./docker/apache/vhost-prod.conf:/etc/apache2/sites-available/000-default.conf

    depends_on:
      - mysql-prod


volumes:
  mysql_data_prod:
